In [2]:
import numpy as np

In [4]:
lista = [1,2,3,4,5,6]
lista_array = np.array(lista)
print(lista_array)

[1 2 3 4 5 6]


In [13]:
np.zeros((5,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.ones((5,10), dtype = float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [34]:
np.random.uniform()

0.17156326128007227

In [36]:
np.random.uniform(size = (5,10) )

array([[0.98163663, 0.4730765 , 0.57797219, 0.40969981, 0.15545849,
        0.64583051, 0.28201387, 0.61733491, 0.18878508, 0.01261068],
       [0.19689616, 0.40917503, 0.23796735, 0.21773153, 0.69550307,
        0.30056048, 0.56409425, 0.97355926, 0.03909549, 0.83463868],
       [0.72587623, 0.70707243, 0.24763045, 0.2586777 , 0.23975571,
        0.78707471, 0.25900559, 0.58786876, 0.99036886, 0.54643825],
       [0.19648418, 0.00203708, 0.0633671 , 0.44333053, 0.06113699,
        0.13133101, 0.60041548, 0.37205016, 0.6798749 , 0.28054683],
       [0.84424811, 0.20758001, 0.50671485, 0.03377305, 0.55148528,
        0.23146992, 0.079701  , 0.88642249, 0.99503598, 0.45652317]])

In [37]:
np.random.normal(size = 10)

array([-0.21329836,  1.60412337,  0.33100357, -0.94893898, -0.98914197,
       -2.03364008, -0.1767175 , -2.11580126,  1.26279334, -2.2189745 ])

In [39]:
np.random.normal(loc = 10, scale = 5, size = 10)

array([6.23149462, 6.8836517 , 3.71010792, 8.21545668, 6.56564028,
       8.75511293, 6.5711193 , 6.70871888, 5.70915156, 6.66153906])

In [42]:
np.random.random_integers(low = 1, high = 7,size = 10)

<ipython-input-42-80f65f1f5c50>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 7 + 1) instead
  np.random.random_integers(low = 1, high = 7,size = 10)


array([1, 7, 3, 1, 6, 2, 2, 1, 1, 2])

In [50]:
dice_throws1 = np.random.randint(1,7,10000)
dice_throws2 = np.random.randint(1,7,10000)

In [51]:
dice_throws1 + dice_throws2 == 8

array([False, False, False, ..., False, False, False])

In [53]:
dice_throws1 + dice_throws2

array([ 6,  6,  5, ..., 10,  7,  7])

In [54]:
np.count_nonzero(dice_throws1 + dice_throws2 == 8)/10000

0.1394

In [48]:
1./6

0.16666666666666666