### Esempio

In [2]:
import numpy as np

In [3]:
dado_alice = np.random.randint(1,7,10)
dado_bob = np.random.randint(1,7,10)
print(dado_alice)
print(dado_bob)

[4 3 5 4 6 5 6 5 5 2]
[4 3 1 4 1 5 6 4 4 1]


In [4]:
punteggi_vittoria_alice = dado_alice[dado_alice>dado_bob]

In [5]:
punteggi_vittoria_alice

array([5, 6, 5, 5, 2])

In [9]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
mat[1,1]

5

In [14]:
terza_colonna = mat[:,2]
terza_colonna

array([3, 6, 9])

In [15]:
terza_colonna[...] = 11
mat

array([[ 1,  2, 11],
       [ 4,  5, 11],
       [ 7,  8, 11]])

In [16]:
terza_colonna.base is mat

True

In [18]:
mat= np.random.randint(0,2, size = (10,10))
print(mat)

[[1 0 0 1 1 0 0 0 1 1]
 [1 0 0 1 0 1 0 0 1 0]
 [1 1 0 1 1 1 1 1 1 0]
 [0 0 0 1 0 1 0 1 1 0]
 [0 0 0 1 0 0 1 1 0 1]
 [0 1 0 0 1 1 1 0 1 0]
 [0 1 0 1 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 0 1 0]
 [1 1 0 0 0 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0]]


In [19]:
mat[:,9] = 0
mat[:,0] = 0
mat[0] = 0
mat[9] = 0
print(mat)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 1 0]
 [0 1 0 1 1 1 1 1 1 0]
 [0 0 0 1 0 1 0 1 1 0]
 [0 0 0 1 0 0 1 1 0 0]
 [0 1 0 0 1 1 1 0 1 0]
 [0 1 0 1 0 1 0 0 1 0]
 [0 1 1 0 0 1 0 0 1 0]
 [0 1 0 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [21]:
mat[:,9] = temp_array = np.random.randint(0,10, 10)
mat[:,0] = temp_array = np.random.randint(0,10, 10)
mat[0] = temp_array = np.random.randint(0,10, 10)
mat[9] = temp_array = np.random.randint(0,10, 10)
print(mat)

[[4 3 8 9 0 5 7 0 1 3]
 [4 0 0 1 0 1 0 0 1 3]
 [3 1 0 1 1 1 1 1 1 2]
 [5 0 0 1 0 1 0 1 1 1]
 [9 0 0 1 0 0 1 1 0 7]
 [5 1 0 0 1 1 1 0 1 8]
 [2 1 0 1 0 1 0 0 1 5]
 [9 1 1 0 0 1 0 0 1 9]
 [7 1 0 0 0 1 0 1 1 9]
 [0 6 5 2 1 4 4 6 1 3]]
