In [3]:
import numpy as np

### Es 1

 Creare una matrice fatta scacchiera 8x8 alternando 0 e 1 (la prima cella è uno 0) 

In [6]:
scacchiera = np.zeros(shape=(8,8))
scacchiera

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
indici = np.array([[i,j] for i in range(8) for j in range(8) if (i+j)%2==1])
indici

array([[0, 1],
       [0, 3],
       [0, 5],
       [0, 7],
       [1, 0],
       [1, 2],
       [1, 4],
       [1, 6],
       [2, 1],
       [2, 3],
       [2, 5],
       [2, 7],
       [3, 0],
       [3, 2],
       [3, 4],
       [3, 6],
       [4, 1],
       [4, 3],
       [4, 5],
       [4, 7],
       [5, 0],
       [5, 2],
       [5, 4],
       [5, 6],
       [6, 1],
       [6, 3],
       [6, 5],
       [6, 7],
       [7, 0],
       [7, 2],
       [7, 4],
       [7, 6]])

In [12]:
scacchiera = np.zeros(shape=(8,8))
scacchiera [indici.T[0],indici.T[1]]=1
scacchiera

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### Es 2

Considerando l'array: Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], generare un array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].

In [13]:
Z = np.arange(1,15)
Z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
indici= np.array([i+j for i in range(0,11) for j in range(0,4)])
indici

array([ 0,  1,  2,  3,  1,  2,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6,  4,
        5,  6,  7,  5,  6,  7,  8,  6,  7,  8,  9,  7,  8,  9, 10,  8,  9,
       10, 11,  9, 10, 11, 12, 10, 11, 12, 13])

In [15]:
Z[indici].reshape((11,-1))

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

### Es 3

Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile.

In [24]:
altezze = np.array([180, 171, 182, 175, 177, 175, 179, 185, 185, 190, 176])
altezze

array([180, 171, 182, 175, 177, 175, 179, 185, 185, 190, 176])

In [25]:
media = np.average(altezze)
media

179.54545454545453

In [41]:
altezze_quadrato = altezze**2
altezze_quadrato

array([32400, 29241, 33124, 30625, 31329, 30625, 32041, 34225, 34225,
       36100, 30976], dtype=int32)

In [42]:
media_quadrato = np.average(altezze_quadrato)
media_quadrato

32264.636363636364

In [43]:
devstd = np.sqrt(media_quadrato-media**2)
devstd

5.297746285212631

In [47]:
np.random.normal(media,devstd,20)

array([178.91292479, 187.07831573, 182.21221858, 183.52620115,
       169.16631769, 176.57448264, 176.91988147, 181.67474515,
       183.46935656, 180.01773891, 190.65945498, 181.76199826,
       177.75445391, 169.72311769, 174.79979851, 177.59510144,
       184.54420203, 168.01087662, 184.8853387 , 173.6949119 ])

### Es 4

Creare una matrice fatta come un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1)

In [22]:
s = 10
Z = np.zeros(shape=(s,s))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [23]:
for i in range(s-1,-1,-1):
    Z[:,i] = i+1
    Z[:,s-i-1] = i+1
    Z[i,:] = i+1
    Z[s-i-1,:] = i+1
    
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 4., 5., 5., 4., 3., 2., 1.],
       [1., 2., 3., 4., 5., 5., 4., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])